// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdKK1iCC7hCNa1SXUsHF79HWLVo2wo1Ko',
    appId: '1:969851857507:web:035484fd61e18b68daa656',
    messagingSenderId: '969851857507',
    projectId: 'flatnotes',
    authDomain: 'flatnotes-bcf84.firebaseapp.com',
    storageBucket: 'flatnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgnXJPd4cOxLVP-LubdogkvMeH_YRTjL8',
    appId: '1:969851857507:android:f6712c06ec0fa7a5daa656',
    messagingSenderId: '969851857507',
    projectId: 'flatnotes',
    storageBucket: 'flatnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCHssK9tR0eEh6h5bGiiVCP90QsRbf6N8',
    appId: '1:969851857507:ios:db155e91369264d6daa656',
    messagingSenderId: '969851857507',
    projectId: 'flatnotes',
    storageBucket: 'flatnotes.appspot.com',
    iosClientId: '969851857507-g0d41gpbk1ann2ffpu5r720epcubil9k.apps.googleusercontent.com',
    iosBundleId: 'com.nikitin.flatnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCHssK9tR0eEh6h5bGiiVCP90QsRbf6N8',
    appId: '1:969851857507:ios:db155e91369264d6daa656',
    messagingSenderId: '969851857507',
    projectId: 'flatnotes',
    storageBucket: 'flatnotes.appspot.com',
    iosClientId: '969851857507-g0d41gpbk1ann2ffpu5r720epcubil9k.apps.googleusercontent.com',
    iosBundleId: 'com.nikitin.flatnotes',
  );
}
